// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Amount int32  `json:"amount"`
}
